/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { PetstoreCore } from "../core.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { PetstoreError } from "../models/errors/petstoreerror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";
import * as types$ from "../types/primitives.js";

/**
 * Add a new pet to the store.
 *
 * @remarks
 * Add a new pet to the store.
 *
 * If set, this operation will use {@link Security.petstoreAuth} from the global security.
 */
export function petAddPetRaw(
  client: PetstoreCore,
  request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.AddPetRawResponse | undefined,
    | PetstoreError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: PetstoreCore,
  request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.AddPetRawResponse | undefined,
      | PetstoreError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.parse(
        z.union([
          z.custom<ReadableStream<Uint8Array>>(x =>
            x instanceof ReadableStream
          ),
          z.custom<Blob>(x => x instanceof Blob),
          z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
          z.custom<Uint8Array>(x => x instanceof Uint8Array),
        ]),
        value,
      ),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = payload instanceof Uint8Array
    ? new Uint8Array(payload).buffer
    : payload;

  const path = pathToFunc("/pet")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/xml",
    Accept: "application/json;q=1, application/xml;q=0",
  }));

  const secConfig = await extractSecurity(client._options.petstoreAuth);
  const securityInput = secConfig == null ? {} : { petstoreAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput, [0]);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "addPet_raw",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.petstoreAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const [result] = await M.match<
    operations.AddPetRawResponse | undefined,
    | PetstoreError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, types$.optional(operations.AddPetRawResponse$inboundSchema)),
    M.bytes(200, types$.optional(operations.AddPetRawResponse$inboundSchema), {
      ctype: "application/xml",
    }),
    M.fail([400, 422, "4XX"]),
    M.fail("5XX"),
    M.nil(
      "default",
      types$.optional(operations.AddPetRawResponse$inboundSchema),
    ),
  )(response, req);
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
