/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Available scopes for the petstore_auth OAuth 2.0 scheme (implicit flow).
 */
export type PetstoreAuthOAuth2Scope =
  /**
   * modify pets in your account
   */
  | "write:pets"
  /**
   * read your pets
   */
  | "read:pets";
