/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petAddPetForm } from "../funcs/petAddPetForm.js";
import { petAddPetJson } from "../funcs/petAddPetJson.js";
import { petAddPetRaw } from "../funcs/petAddPetRaw.js";
import { petDeletePet } from "../funcs/petDeletePet.js";
import { petFetchPetById } from "../funcs/petFetchPetById.js";
import { petFindPetsByStatus } from "../funcs/petFindPetsByStatus.js";
import { petFindPetsByTags } from "../funcs/petFindPetsByTags.js";
import { petUpdatePetForm } from "../funcs/petUpdatePetForm.js";
import { petUpdatePetJson } from "../funcs/petUpdatePetJson.js";
import { petUpdatePetRaw } from "../funcs/petUpdatePetRaw.js";
import { petUpdatePetWithForm } from "../funcs/petUpdatePetWithForm.js";
import { petUploadFile } from "../funcs/petUploadFile.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Pet extends ClientSDK {
  /**
   * Update an existing pet.
   *
   * @remarks
   * Update an existing pet by Id.
   */
  async updatePetJson(
    request: components.Pet,
    options?: RequestOptions,
  ): Promise<operations.UpdatePetJsonResponse | undefined> {
    return unwrapAsync(petUpdatePetJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing pet.
   *
   * @remarks
   * Update an existing pet by Id.
   */
  async updatePetRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<operations.UpdatePetRawResponse | undefined> {
    return unwrapAsync(petUpdatePetRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing pet.
   *
   * @remarks
   * Update an existing pet by Id.
   */
  async updatePetForm(
    request: components.Pet,
    options?: RequestOptions,
  ): Promise<operations.UpdatePetFormResponse | undefined> {
    return unwrapAsync(petUpdatePetForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Add a new pet to the store.
   *
   * @remarks
   * Add a new pet to the store.
   */
  async addPetJson(
    request: components.Pet,
    options?: RequestOptions,
  ): Promise<operations.AddPetJsonResponse | undefined> {
    return unwrapAsync(petAddPetJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Add a new pet to the store.
   *
   * @remarks
   * Add a new pet to the store.
   */
  async addPetRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<operations.AddPetRawResponse | undefined> {
    return unwrapAsync(petAddPetRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Add a new pet to the store.
   *
   * @remarks
   * Add a new pet to the store.
   */
  async addPetForm(
    request: components.Pet,
    options?: RequestOptions,
  ): Promise<operations.AddPetFormResponse | undefined> {
    return unwrapAsync(petAddPetForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Finds Pets by status.
   *
   * @remarks
   * Multiple status values can be provided with comma separated strings.
   */
  async findPetsByStatus(
    status: operations.Status | undefined,
    options?: RequestOptions,
  ): Promise<operations.FindPetsByStatusResponse | undefined> {
    return unwrapAsync(petFindPetsByStatus(
      this,
      status,
      options,
    ));
  }

  /**
   * Finds Pets by tags.
   *
   * @remarks
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   */
  async findPetsByTags(
    tags: Array<string>,
    options?: RequestOptions,
  ): Promise<operations.FindPetsByTagsResponse | undefined> {
    return unwrapAsync(petFindPetsByTags(
      this,
      tags,
      options,
    ));
  }

  /**
   * Find pet by ID.
   *
   * @remarks
   * Returns a single pet.
   */
  async fetchPetById(
    security: operations.FetchPetByIdSecurity,
    petId: number,
    options?: RequestOptions,
  ): Promise<operations.FetchPetByIdResponse | undefined> {
    return unwrapAsync(petFetchPetById(
      this,
      security,
      petId,
      options,
    ));
  }

  /**
   * Updates a pet in the store with form data.
   *
   * @remarks
   * Updates a pet resource based on the form data.
   */
  async updatePetWithForm(
    petId: number,
    name?: string | undefined,
    status?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.UpdatePetWithFormResponse | undefined> {
    return unwrapAsync(petUpdatePetWithForm(
      this,
      petId,
      name,
      status,
      options,
    ));
  }

  /**
   * Deletes a pet.
   *
   * @remarks
   * Delete a pet.
   */
  async deletePet(
    petId: number,
    apiKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(petDeletePet(
      this,
      petId,
      apiKey,
      options,
    ));
  }

  /**
   * Uploads an image.
   *
   * @remarks
   * Upload image of the pet.
   */
  async uploadFile(
    petId: number,
    additionalMetadata?: string | undefined,
    body?:
      | ReadableStream<Uint8Array>
      | Blob
      | ArrayBuffer
      | Uint8Array
      | undefined,
    options?: RequestOptions,
  ): Promise<components.ApiResponse | undefined> {
    return unwrapAsync(petUploadFile(
      this,
      petId,
      additionalMetadata,
      body,
      options,
    ));
  }
}
