/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storeDeleteOrder } from "../funcs/storeDeleteOrder.js";
import { storeGetInventory } from "../funcs/storeGetInventory.js";
import { storeGetOrderById } from "../funcs/storeGetOrderById.js";
import { storePlaceOrderForm } from "../funcs/storePlaceOrderForm.js";
import { storePlaceOrderJson } from "../funcs/storePlaceOrderJson.js";
import { storePlaceOrderRaw } from "../funcs/storePlaceOrderRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Store extends ClientSDK {
  /**
   * Returns pet inventories by status.
   *
   * @remarks
   * Returns a map of status codes to quantities.
   */
  async getInventory(
    security: operations.GetInventorySecurity,
    options?: RequestOptions,
  ): Promise<{ [k: string]: number } | undefined> {
    return unwrapAsync(storeGetInventory(
      this,
      security,
      options,
    ));
  }

  /**
   * Place an order for a pet.
   *
   * @remarks
   * Place a new order in the store.
   */
  async placeOrderJson(
    request?: components.Order | undefined,
    options?: RequestOptions,
  ): Promise<components.Order | undefined> {
    return unwrapAsync(storePlaceOrderJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Place an order for a pet.
   *
   * @remarks
   * Place a new order in the store.
   */
  async placeOrderRaw(
    request?:
      | ReadableStream<Uint8Array>
      | Blob
      | ArrayBuffer
      | Uint8Array
      | undefined,
    options?: RequestOptions,
  ): Promise<components.Order | undefined> {
    return unwrapAsync(storePlaceOrderRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Place an order for a pet.
   *
   * @remarks
   * Place a new order in the store.
   */
  async placeOrderForm(
    request?: components.Order | undefined,
    options?: RequestOptions,
  ): Promise<components.Order | undefined> {
    return unwrapAsync(storePlaceOrderForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Find purchase order by ID.
   *
   * @remarks
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   */
  async getOrderById(
    orderId: number,
    options?: RequestOptions,
  ): Promise<operations.GetOrderByIdResponse | undefined> {
    return unwrapAsync(storeGetOrderById(
      this,
      orderId,
      options,
    ));
  }

  /**
   * Delete purchase order by identifier.
   *
   * @remarks
   * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
   */
  async deleteOrder(
    orderId: number,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(storeDeleteOrder(
      this,
      orderId,
      options,
    ));
  }
}
