/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemHealthCheck } from "../funcs/systemHealthCheck.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class System extends ClientSDK {
  /**
   * Health check endpoint.
   *
   * @remarks
   * Returns the health status of the API.
   */
  async healthCheck(
    options?: RequestOptions,
  ): Promise<operations.HealthCheckResponseBody> {
    return unwrapAsync(systemHealthCheck(
      this,
      options,
    ));
  }
}
