/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemGetHealthStatus } from "../funcs/systemGetHealthStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class System extends ClientSDK {
  /**
   * Get API health status.
   *
   * @remarks
   * Returns detailed health status of the API including uptime.
   */
  async getHealthStatus(
    options?: RequestOptions,
  ): Promise<operations.GetHealthStatusResponseBody> {
    return unwrapAsync(systemGetHealthStatus(
      this,
      options,
    ));
  }
}
