/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userCreateUserForm } from "../funcs/userCreateUserForm.js";
import { userCreateUserJson } from "../funcs/userCreateUserJson.js";
import { userCreateUserRaw } from "../funcs/userCreateUserRaw.js";
import { userCreateUsersWithListInput } from "../funcs/userCreateUsersWithListInput.js";
import { userDeleteUser } from "../funcs/userDeleteUser.js";
import { userGetUserByName } from "../funcs/userGetUserByName.js";
import { userLoginUser } from "../funcs/userLoginUser.js";
import { userLogoutUser } from "../funcs/userLogoutUser.js";
import { userUpdateUserForm } from "../funcs/userUpdateUserForm.js";
import { userUpdateUserJson } from "../funcs/userUpdateUserJson.js";
import { userUpdateUserRaw } from "../funcs/userUpdateUserRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class User extends ClientSDK {
  /**
   * Create user.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async createUserJson(
    request?: components.User | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateUserJsonResponse | undefined> {
    return unwrapAsync(userCreateUserJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Create user.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async createUserRaw(
    request?:
      | ReadableStream<Uint8Array>
      | Blob
      | ArrayBuffer
      | Uint8Array
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateUserRawResponse | undefined> {
    return unwrapAsync(userCreateUserRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Create user.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async createUserForm(
    request?: components.User | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateUserFormResponse | undefined> {
    return unwrapAsync(userCreateUserForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Creates list of users with given input array.
   *
   * @remarks
   * Creates list of users with given input array.
   */
  async createUsersWithListInput(
    request?: Array<components.User> | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateUsersWithListInputResponse | undefined> {
    return unwrapAsync(userCreateUsersWithListInput(
      this,
      request,
      options,
    ));
  }

  /**
   * Logs user into the system.
   *
   * @remarks
   * Log into the system.
   */
  async loginUser(
    username?: string | undefined,
    password?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.LoginUserResponse | undefined> {
    return unwrapAsync(userLoginUser(
      this,
      username,
      password,
      options,
    ));
  }

  /**
   * Logs out current logged in user session.
   *
   * @remarks
   * Log user out of the system.
   */
  async logoutUser(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(userLogoutUser(
      this,
      options,
    ));
  }

  /**
   * Get user by user name.
   *
   * @remarks
   * Get user detail based on username.
   */
  async getUserByName(
    username: string,
    options?: RequestOptions,
  ): Promise<operations.GetUserByNameResponse | undefined> {
    return unwrapAsync(userGetUserByName(
      this,
      username,
      options,
    ));
  }

  /**
   * Update user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async updateUserJson(
    username: string,
    body?: components.User | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(userUpdateUserJson(
      this,
      username,
      body,
      options,
    ));
  }

  /**
   * Update user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async updateUserRaw(
    username: string,
    body?:
      | ReadableStream<Uint8Array>
      | Blob
      | ArrayBuffer
      | Uint8Array
      | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(userUpdateUserRaw(
      this,
      username,
      body,
      options,
    ));
  }

  /**
   * Update user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async updateUserForm(
    username: string,
    body?: components.User | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(userUpdateUserForm(
      this,
      username,
      body,
      options,
    ));
  }

  /**
   * Delete user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async deleteUser(
    username: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(userDeleteUser(
      this,
      username,
      options,
    ));
  }
}
