/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the petstore-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx systemGetHealthStatus.example.ts
 */

import { Petstore } from "petstore-sdk";

const petstore = new Petstore({
  serverURL: "https://api.example.com",
  petstoreAuth: "<YOUR_PETSTORE_AUTH_HERE>",
});

async function main() {
  const result = await petstore.system.getHealthStatus();

  console.log(result);
}

main().catch(console.error);
