/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AddPetRawResponse = components.Pet | Uint8Array | string;

/** @internal */
export const AddPetRawResponse$inboundSchema: z.ZodMiniType<
  AddPetRawResponse,
  unknown
> = smartUnion([components.Pet$inboundSchema, b64$.zodInbound]);

export function addPetRawResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddPetRawResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddPetRawResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddPetRawResponse' from JSON`,
  );
}
