/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateUserJsonResponse = components.User | Uint8Array | string;

/** @internal */
export const CreateUserJsonResponse$inboundSchema: z.ZodMiniType<
  CreateUserJsonResponse,
  unknown
> = smartUnion([components.User$inboundSchema, b64$.zodInbound]);

export function createUserJsonResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateUserJsonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateUserJsonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateUserJsonResponse' from JSON`,
  );
}
