/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FetchPetByIdSecurity = {
  apiKey?: string | undefined;
  petstoreAuth?: string | undefined;
};

export type FetchPetByIdRequest = {
  /**
   * ID of pet to return
   */
  petId: number;
};

export type FetchPetByIdResponse = components.Pet | Uint8Array | string;

/** @internal */
export type FetchPetByIdSecurity$Outbound = {
  api_key?: string | undefined;
  petstore_auth?: string | undefined;
};

/** @internal */
export const FetchPetByIdSecurity$outboundSchema: z.ZodMiniType<
  FetchPetByIdSecurity$Outbound,
  FetchPetByIdSecurity
> = z.pipe(
  z.object({
    apiKey: z.optional(z.string()),
    petstoreAuth: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKey: "api_key",
      petstoreAuth: "petstore_auth",
    });
  }),
);

export function fetchPetByIdSecurityToJSON(
  fetchPetByIdSecurity: FetchPetByIdSecurity,
): string {
  return JSON.stringify(
    FetchPetByIdSecurity$outboundSchema.parse(fetchPetByIdSecurity),
  );
}

/** @internal */
export type FetchPetByIdRequest$Outbound = {
  petId: number;
};

/** @internal */
export const FetchPetByIdRequest$outboundSchema: z.ZodMiniType<
  FetchPetByIdRequest$Outbound,
  FetchPetByIdRequest
> = z.object({
  petId: z.int(),
});

export function fetchPetByIdRequestToJSON(
  fetchPetByIdRequest: FetchPetByIdRequest,
): string {
  return JSON.stringify(
    FetchPetByIdRequest$outboundSchema.parse(fetchPetByIdRequest),
  );
}

/** @internal */
export const FetchPetByIdResponse$inboundSchema: z.ZodMiniType<
  FetchPetByIdResponse,
  unknown
> = smartUnion([components.Pet$inboundSchema, b64$.zodInbound]);

export function fetchPetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchPetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchPetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchPetByIdResponse' from JSON`,
  );
}
