/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Status values that need to be considered for filter
 */
export const Status = {
  Available: "available",
  Pending: "pending",
  Sold: "sold",
} as const;
/**
 * Status values that need to be considered for filter
 */
export type Status = ClosedEnum<typeof Status>;

export type FindPetsByStatusRequest = {
  /**
   * Status values that need to be considered for filter
   */
  status?: Status | undefined;
};

export type FindPetsByStatusResponse =
  | Array<components.Pet>
  | Uint8Array
  | string;

/** @internal */
export const Status$outboundSchema: z.ZodMiniEnum<typeof Status> = z.enum(
  Status,
);

/** @internal */
export type FindPetsByStatusRequest$Outbound = {
  status: string;
};

/** @internal */
export const FindPetsByStatusRequest$outboundSchema: z.ZodMiniType<
  FindPetsByStatusRequest$Outbound,
  FindPetsByStatusRequest
> = z.object({
  status: z._default(Status$outboundSchema, "available"),
});

export function findPetsByStatusRequestToJSON(
  findPetsByStatusRequest: FindPetsByStatusRequest,
): string {
  return JSON.stringify(
    FindPetsByStatusRequest$outboundSchema.parse(findPetsByStatusRequest),
  );
}

/** @internal */
export const FindPetsByStatusResponse$inboundSchema: z.ZodMiniType<
  FindPetsByStatusResponse,
  unknown
> = smartUnion([z.array(components.Pet$inboundSchema), b64$.zodInbound]);

export function findPetsByStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<FindPetsByStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindPetsByStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindPetsByStatusResponse' from JSON`,
  );
}
