/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FindPetsByTagsRequest = {
  /**
   * Tags to filter by
   */
  tags: Array<string>;
};

export type FindPetsByTagsResponse =
  | Array<components.Pet>
  | Uint8Array
  | string;

/** @internal */
export type FindPetsByTagsRequest$Outbound = {
  tags: Array<string>;
};

/** @internal */
export const FindPetsByTagsRequest$outboundSchema: z.ZodMiniType<
  FindPetsByTagsRequest$Outbound,
  FindPetsByTagsRequest
> = z.object({
  tags: z.array(z.string()),
});

export function findPetsByTagsRequestToJSON(
  findPetsByTagsRequest: FindPetsByTagsRequest,
): string {
  return JSON.stringify(
    FindPetsByTagsRequest$outboundSchema.parse(findPetsByTagsRequest),
  );
}

/** @internal */
export const FindPetsByTagsResponse$inboundSchema: z.ZodMiniType<
  FindPetsByTagsResponse,
  unknown
> = smartUnion([z.array(components.Pet$inboundSchema), b64$.zodInbound]);

export function findPetsByTagsResponseFromJSON(
  jsonString: string,
): SafeParseResult<FindPetsByTagsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FindPetsByTagsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FindPetsByTagsResponse' from JSON`,
  );
}
