/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * API is healthy
 */
export type GetHealthStatusResponseBody = {
  healthy: boolean;
  apiVersion: string;
  /**
   * Uptime in seconds
   */
  uptime?: number | undefined;
};

/** @internal */
export const GetHealthStatusResponseBody$inboundSchema: z.ZodMiniType<
  GetHealthStatusResponseBody,
  unknown
> = z.object({
  healthy: types.boolean(),
  apiVersion: types.string(),
  uptime: types.optional(types.number()),
});

export function getHealthStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetHealthStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetHealthStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetHealthStatusResponseBody' from JSON`,
  );
}
