/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetInventorySecurity = {
  apiKey: string;
};

/** @internal */
export type GetInventorySecurity$Outbound = {
  api_key: string;
};

/** @internal */
export const GetInventorySecurity$outboundSchema: z.ZodMiniType<
  GetInventorySecurity$Outbound,
  GetInventorySecurity
> = z.pipe(
  z.object({
    apiKey: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKey: "api_key",
    });
  }),
);

export function getInventorySecurityToJSON(
  getInventorySecurity: GetInventorySecurity,
): string {
  return JSON.stringify(
    GetInventorySecurity$outboundSchema.parse(getInventorySecurity),
  );
}
