/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetOrderByIdRequest = {
  /**
   * ID of order that needs to be fetched
   */
  orderId: number;
};

export type GetOrderByIdResponse = components.Order | Uint8Array | string;

/** @internal */
export type GetOrderByIdRequest$Outbound = {
  orderId: number;
};

/** @internal */
export const GetOrderByIdRequest$outboundSchema: z.ZodMiniType<
  GetOrderByIdRequest$Outbound,
  GetOrderByIdRequest
> = z.object({
  orderId: z.int(),
});

export function getOrderByIdRequestToJSON(
  getOrderByIdRequest: GetOrderByIdRequest,
): string {
  return JSON.stringify(
    GetOrderByIdRequest$outboundSchema.parse(getOrderByIdRequest),
  );
}

/** @internal */
export const GetOrderByIdResponse$inboundSchema: z.ZodMiniType<
  GetOrderByIdResponse,
  unknown
> = smartUnion([components.Order$inboundSchema, b64$.zodInbound]);

export function getOrderByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrderByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrderByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrderByIdResponse' from JSON`,
  );
}
