/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPetByIdSecurity = {
  apiKey?: string | undefined;
  petstoreAuth?: string | undefined;
};

export type GetPetByIdRequest = {
  /**
   * ID of pet to return
   */
  petId: number;
};

export type GetPetByIdResponse = components.Pet | Uint8Array | string;

/** @internal */
export type GetPetByIdSecurity$Outbound = {
  api_key?: string | undefined;
  petstore_auth?: string | undefined;
};

/** @internal */
export const GetPetByIdSecurity$outboundSchema: z.ZodMiniType<
  GetPetByIdSecurity$Outbound,
  GetPetByIdSecurity
> = z.pipe(
  z.object({
    apiKey: z.optional(z.string()),
    petstoreAuth: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiKey: "api_key",
      petstoreAuth: "petstore_auth",
    });
  }),
);

export function getPetByIdSecurityToJSON(
  getPetByIdSecurity: GetPetByIdSecurity,
): string {
  return JSON.stringify(
    GetPetByIdSecurity$outboundSchema.parse(getPetByIdSecurity),
  );
}

/** @internal */
export type GetPetByIdRequest$Outbound = {
  petId: number;
};

/** @internal */
export const GetPetByIdRequest$outboundSchema: z.ZodMiniType<
  GetPetByIdRequest$Outbound,
  GetPetByIdRequest
> = z.object({
  petId: z.int(),
});

export function getPetByIdRequestToJSON(
  getPetByIdRequest: GetPetByIdRequest,
): string {
  return JSON.stringify(
    GetPetByIdRequest$outboundSchema.parse(getPetByIdRequest),
  );
}

/** @internal */
export const GetPetByIdResponse$inboundSchema: z.ZodMiniType<
  GetPetByIdResponse,
  unknown
> = smartUnion([components.Pet$inboundSchema, b64$.zodInbound]);

export function getPetByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPetByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPetByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPetByIdResponse' from JSON`,
  );
}
