/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * API is healthy
 */
export type HealthCheckResponseBody = {
  status?: string | undefined;
  version?: string | undefined;
};

/** @internal */
export const HealthCheckResponseBody$inboundSchema: z.ZodMiniType<
  HealthCheckResponseBody,
  unknown
> = z.object({
  status: types.optional(types.string()),
  version: types.optional(types.string()),
});

export function healthCheckResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<HealthCheckResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HealthCheckResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HealthCheckResponseBody' from JSON`,
  );
}
