/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateUserRawRequest = {
  /**
   * name that need to be deleted
   */
  username: string;
  /**
   * Update an existent user in the store
   */
  body?:
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array
    | undefined;
};

/** @internal */
export type UpdateUserRawRequest$Outbound = {
  username: string;
  body?:
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array
    | undefined;
};

/** @internal */
export const UpdateUserRawRequest$outboundSchema: z.ZodMiniType<
  UpdateUserRawRequest$Outbound,
  UpdateUserRawRequest
> = z.object({
  username: z.string(),
  body: z.optional(
    z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  ),
});

export function updateUserRawRequestToJSON(
  updateUserRawRequest: UpdateUserRawRequest,
): string {
  return JSON.stringify(
    UpdateUserRawRequest$outboundSchema.parse(updateUserRawRequest),
  );
}
