/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePetFormResponse = components.Pet | Uint8Array | string;

/** @internal */
export const UpdatePetFormResponse$inboundSchema: z.ZodMiniType<
  UpdatePetFormResponse,
  unknown
> = smartUnion([components.Pet$inboundSchema, b64$.zodInbound]);

export function updatePetFormResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePetFormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePetFormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePetFormResponse' from JSON`,
  );
}
