/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type UpdateUserFormRequest = {
  /**
   * name that need to be deleted
   */
  username: string;
  /**
   * Update an existent user in the store
   */
  body?: components.User | undefined;
};

/** @internal */
export type UpdateUserFormRequest$Outbound = {
  username: string;
  body?: components.User$Outbound | undefined;
};

/** @internal */
export const UpdateUserFormRequest$outboundSchema: z.ZodMiniType<
  UpdateUserFormRequest$Outbound,
  UpdateUserFormRequest
> = z.object({
  username: z.string(),
  body: z.optional(components.User$outboundSchema),
});

export function updateUserFormRequestToJSON(
  updateUserFormRequest: UpdateUserFormRequest,
): string {
  return JSON.stringify(
    UpdateUserFormRequest$outboundSchema.parse(updateUserFormRequest),
  );
}
