/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type UpdateUserJsonRequest = {
  /**
   * name that need to be deleted
   */
  username: string;
  /**
   * Update an existent user in the store
   */
  body?: components.User | undefined;
};

/** @internal */
export type UpdateUserJsonRequest$Outbound = {
  username: string;
  body?: components.User$Outbound | undefined;
};

/** @internal */
export const UpdateUserJsonRequest$outboundSchema: z.ZodMiniType<
  UpdateUserJsonRequest$Outbound,
  UpdateUserJsonRequest
> = z.object({
  username: z.string(),
  body: z.optional(components.User$outboundSchema),
});

export function updateUserJsonRequestToJSON(
  updateUserJsonRequest: UpdateUserJsonRequest,
): string {
  return JSON.stringify(
    UpdateUserJsonRequest$outboundSchema.parse(updateUserJsonRequest),
  );
}
