/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smartUnion.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePetWithFormRequest = {
  /**
   * ID of pet that needs to be updated
   */
  petId: number;
  /**
   * Name of pet that needs to be updated
   */
  name?: string | undefined;
  /**
   * Status of pet that needs to be updated
   */
  status?: string | undefined;
};

export type UpdatePetWithFormResponse = components.Pet | Uint8Array | string;

/** @internal */
export type UpdatePetWithFormRequest$Outbound = {
  petId: number;
  name?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const UpdatePetWithFormRequest$outboundSchema: z.ZodMiniType<
  UpdatePetWithFormRequest$Outbound,
  UpdatePetWithFormRequest
> = z.object({
  petId: z.int(),
  name: z.optional(z.string()),
  status: z.optional(z.string()),
});

export function updatePetWithFormRequestToJSON(
  updatePetWithFormRequest: UpdatePetWithFormRequest,
): string {
  return JSON.stringify(
    UpdatePetWithFormRequest$outboundSchema.parse(updatePetWithFormRequest),
  );
}

/** @internal */
export const UpdatePetWithFormResponse$inboundSchema: z.ZodMiniType<
  UpdatePetWithFormResponse,
  unknown
> = smartUnion([components.Pet$inboundSchema, b64$.zodInbound]);

export function updatePetWithFormResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePetWithFormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePetWithFormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePetWithFormResponse' from JSON`,
  );
}
